apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod-pod
  labels:
    app: nginx
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
    - name: log-watcher
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["tail -n+1 -F /var/log/nginx/access.log"]
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx

  volumes:
    - name: nginx-cache
      emptyDir: {}
    - name: nginx-logs
      emptyDir: {}
